// Code generated by "stringer -type ActiveState -output active_state_string.go"; DO NOT EDIT.

package safeweb_lib_num

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Inactive-0]
	_ = x[Active-1]
}

const _ActiveState_name = "InactiveActive"

var _ActiveState_index = [...]uint8{0, 8, 14}

func (i ActiveState) String() string {
	if i < 0 || i >= ActiveState(len(_ActiveState_index)-1) {
		return "ActiveState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ActiveState_name[_ActiveState_index[i]:_ActiveState_index[i+1]]
}
