CREATE TABLE IF NOT EXISTS `laiit` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `ma_ck` varchar(15) COLLATE utf8mb4_unicode_ci NOT NULL,
  `gia_mua` int(10) unsigned NOT NULL,
  `khoi_luong` int(10) unsigned NOT NULL,
  `tien_mua` int(10) unsigned NOT NULL,
  `ngay_mua` timestamp NULL DEFAULT NULL,
  `gia_ban_max` int(10) unsigned NOT NULL,
  `lai_max` int(10) DEFAULT NULL,
  `ty_le_max` float DEFAULT NULL,
  `ngay_max` timestamp NULL DEFAULT NULL,
  `gia_ban_hom_nay` int(10) unsigned DEFAULT NULL,
  `lai_hom_nay` int(10) DEFAULT NULL,
  `ty_le_hom_nay` float DEFAULT NULL,
  `ngay_hom_nay` timestamp NULL DEFAULT NULL,
  `so_ngay` int(10) unsigned DEFAULT NULL,
  `tien_lo` int(11) DEFAULT NULL,
  `ty_le_lo` float DEFAULT NULL,
  `status` enum('buy','risk','sale','done') COLLATE utf8mb4_unicode_ci DEFAULT 'buy',
  `notify` enum('nope','scrape','scraped','calculate','calculated') COLLATE utf8mb4_unicode_ci DEFAULT 'nope',
  `created_by` int(10) unsigned DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT current_timestamp(),
  `updated_by` int(10) unsigned DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL ON UPDATE current_timestamp(),
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC;