// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package user

import (
	"github.com/gocraft/dbr/v2"
)

// Injectors from wire.go:

func InitializeServer(conn *dbr.Connection) *Server {
	repository := NewRepository(conn)
	service := NewService(repository)
	server := NewServer(service)
	return server
}

func InitializeService(conn *dbr.Connection) *Service {
	repository := NewRepository(conn)
	service := NewService(repository)
	return service
}
