time_zone: "UTC" # Asia/Ho_Chi_Minh
server:
  grpc:
    host: 0.0.0.0
    port: 10443
  http:
    host: 0.0.0.0
    port: 10088
log:
  level: debug # debug, info, warn, error, dpanic, panic, fatal
  mode: development # production
  encoding: console # json
mysql:
  host: localhost
  port: 3306
  database: safe-server
  username: root
  password: 123456
  options: ?parseTime=true
migrations_folder: file://migrations
captchaKey: 6LcUv5MaAAAAAP884oFADM8VYdl5Y1BqADhBj1Dv
service_backend:
  pass: true
service_engine:
  pass: true
webroot: C:\Temp\nextweb\mystocks\scrapstocks\out