// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package task_campaign

import (
	"github.com/go-redis/redis/v8"
	"github.com/gocraft/dbr/v2"
)

// Injectors from wire.go:

func InitializeService(conn *dbr.Connection, redis2 *redis.Client) *Service {
	repository := NewRepository(conn, redis2)
	service := NewService(repository)
	return service
}
